<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StudentAssessmentTestTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('student_assessment_test')->delete();
        
        \DB::table('student_assessment_test')->insert(array (
            0 => 
            array (
                'question_id' => 1,
                'question_text' => 'What are the four major components of a computer?',
                'answer_1' => 'Input Devices- CPU- Storage- Output Devices',
                'answer_2' => 'Input Devices- Processing Unit- Storage- Output Devices',
                'answer_3' => 'Motherboard- Processing Unit- Storage- Output Devices',
                'answer_4' => 'Input Devices- Processing Unit- Memory- Output Devices',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 29,
                'weightage' => 4.0,
                'levels' => 'Easy',
            ),
            1 => 
            array (
                'question_id' => 2,
                'question_text' => 'Which one has two examples of output devices?',
                'answer_1' => 'Monitor and scanner',
                'answer_2' => 'Speaker and keyboard',
                'answer_3' => 'Printer and scanner',
                'answer_4' => 'Speaker and printer',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 44,
                'weightage' => 14.0,
                'levels' => 'Easy',
            ),
            2 => 
            array (
                'question_id' => 3,
                'question_text' => 'What is the brain of the computer?',
                'answer_1' => 'Motherboard',
                'answer_2' => 'Memory',
                'answer_3' => 'CPU',
                'answer_4' => 'NIC',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 32,
                'weightage' => 57.0,
                'levels' => 'Hard',
            ),
            3 => 
            array (
                'question_id' => 4,
                'question_text' => 'Application software…',
                'answer_1' => 'Tells the computer components what to do',
                'answer_2' => 'Let\'s the computer interact with the user',
                'answer_3' => 'Let\'s the user perform a task.',
                'answer_4' => 'Is encoded on a piece of hardware.',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 29,
                'weightage' => 43.0,
                'levels' => 'Medium',
            ),
            4 => 
            array (
                'question_id' => 5,
                'question_text' => 'What allows multiple programs to run on a computer?',
                'answer_1' => 'NIC',
                'answer_2' => 'OS',
                'answer_3' => 'API',
                'answer_4' => 'GUI',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 48,
                'weightage' => 44.0,
                'levels' => 'Medium',
            ),
            5 => 
            array (
                'question_id' => 6,
                'question_text' => 'When was the world wide we invented?',
                'answer_1' => '1974',
                'answer_2' => '1982',
                'answer_3' => '1991',
                'answer_4' => '1999',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 51,
                'weightage' => 91.0,
                'levels' => 'Expert',
            ),
            6 => 
            array (
                'question_id' => 7,
                'question_text' => 'Everything physical in a computer is attached to the…',
                'answer_1' => 'Hard drive',
                'answer_2' => 'CPU',
                'answer_3' => 'Memory',
                'answer_4' => 'Motherboard',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 13,
                'weightage' => 20.0,
                'levels' => 'Easy',
            ),
            7 => 
            array (
                'question_id' => 8,
                'question_text' => 'Information that is broken down into small chunks before it is sent to another computer are called...',
                'answer_1' => 'Letters',
                'answer_2' => 'Messages',
                'answer_3' => 'Packets',
                'answer_4' => 'Packages',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 10,
                'weightage' => 29.0,
                'levels' => 'Medium',
            ),
            8 => 
            array (
                'question_id' => 9,
                'question_text' => 'What does GUI stand for....?',
                'answer_1' => 'Graphical User Interim',
                'answer_2' => 'Geographical User Interruption',
                'answer_3' => 'Graphical User Interface',
                'answer_4' => 'Gain Upper Intensity',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 13,
                'weightage' => 85.0,
                'levels' => 'Expert',
            ),
            9 => 
            array (
                'question_id' => 10,
                'question_text' => 'What type of software is free to try but then you have to buy?',
                'answer_1' => 'Commercial',
                'answer_2' => 'Shareware',
                'answer_3' => 'Opensource',
                'answer_4' => 'Microsoft Word',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 32,
                'weightage' => 36.0,
                'levels' => 'Medium',
            ),
            10 => 
            array (
                'question_id' => 11,
                'question_text' => 'The Miss Porters Network is a',
                'answer_1' => 'MAN',
                'answer_2' => 'SAN',
                'answer_3' => 'WAN',
                'answer_4' => 'LAN',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 20,
                'weightage' => 25.0,
                'levels' => 'Easy',
            ),
            11 => 
            array (
                'question_id' => 12,
                'question_text' => 'Attributes of an object are also known as',
                'answer_1' => 'Methods',
                'answer_2' => 'Properties',
                'answer_3' => 'Classes',
                'answer_4' => 'Functions',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 2,
                'weightage' => 18.0,
                'levels' => 'Easy',
            ),
            12 => 
            array (
                'question_id' => 13,
                'question_text' => 'Which one of the following is the process where an object of one class receives the properties of objects of another class?',
                'answer_1' => 'Encapsulation.',
                'answer_2' => 'Inheritance',
                'answer_3' => 'Polymorphism',
                'answer_4' => 'Modularity',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 53,
                'weightage' => 14.0,
                'levels' => 'Easy',
            ),
            13 => 
            array (
                'question_id' => 14,
                'question_text' => 'What is the main goal of Object oriented programming?',
                'answer_1' => 'Ease of evolution.',
                'answer_2' => 'Monitoring maintenance.',
                'answer_3' => 'Encapsulating code.',
                'answer_4' => 'Information hiding.',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 55,
                'weightage' => 13.0,
                'levels' => 'Easy',
            ),
            14 => 
            array (
                'question_id' => 15,
                'question_text' => 'Polymorphism related to',
                'answer_1' => 'PPO',
                'answer_2' => 'Class',
                'answer_3' => 'OOP',
                'answer_4' => 'OPP',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 17,
                'weightage' => 24.0,
                'levels' => 'Easy',
            ),
            15 => 
            array (
                'question_id' => 16,
                'question_text' => 'Which from the following is a feature that allows us to perform a single action in different ways.',
                'answer_1' => 'Abstraction',
                'answer_2' => 'Polymorphism',
                'answer_3' => 'Encapsulation',
                'answer_4' => 'Inheritance',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 21,
                'weightage' => 80.0,
                'levels' => 'Expert',
            ),
            16 => 
            array (
                'question_id' => 17,
                'question_text' => 'The process by which objects of one class acquire the properties of objects of another class is known as',
                'answer_1' => 'Polymorphism',
                'answer_2' => 'Inheritance',
                'answer_3' => 'Data Hiding',
                'answer_4' => 'Association',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 53,
                'weightage' => 27.0,
                'levels' => 'Medium',
            ),
            17 => 
            array (
                'question_id' => 18,
                'question_text' => 'Pick the term that relates to polymorphism',
                'answer_1' => 'Dynamic binding',
                'answer_2' => 'Static allocation',
                'answer_3' => 'Dynamic allocation',
                'answer_4' => 'Static typing',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 3,
                'weightage' => 97.0,
                'levels' => 'Expert',
            ),
            18 => 
            array (
                'question_id' => 19,
                'question_text' => 'An object that has more than one form is referred to as',
                'answer_1' => 'Polymorphism',
                'answer_2' => 'Inheritance',
                'answer_3' => 'Interface',
                'answer_4' => 'Abstract class',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 52,
                'weightage' => 2.0,
                'levels' => 'Easy',
            ),
            19 => 
            array (
                'question_id' => 20,
                'question_text' => 'Which of the following is not a part of OOP?',
                'answer_1' => 'Information hiding',
                'answer_2' => 'Multitasking',
                'answer_3' => 'Polymorphism',
                'answer_4' => 'Inheritance',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 54,
                'weightage' => 19.0,
                'levels' => 'Easy',
            ),
            20 => 
            array (
                'question_id' => 21,
                'question_text' => 'Hiding complexity can also be termed as',
                'answer_1' => 'Inheritance',
                'answer_2' => 'Overloading',
                'answer_3' => 'Data hiding',
                'answer_4' => 'Abstraction',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 11,
                'weightage' => 86.0,
                'levels' => 'Expert',
            ),
            21 => 
            array (
                'question_id' => 22,
                'question_text' => 'Which of the following concepts of OOPS means exposing only necessary information to client?',
                'answer_1' => 'Encapsulation',
                'answer_2' => 'Abstraction',
                'answer_3' => 'Data hiding',
                'answer_4' => 'Data binding',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 92,
                'weightage' => 75.0,
                'levels' => 'Hard',
            ),
            22 => 
            array (
                'question_id' => 23,
                'question_text' => 'These have identity- state- and behavior.',
                'answer_1' => 'class',
                'answer_2' => 'object',
                'answer_3' => 'method',
                'answer_4' => 'void',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 2,
                'activity_idFK' => 28,
                'weightage' => 16.0,
                'levels' => 'Easy',
            ),
            23 => 
            array (
                'question_id' => 24,
                'question_text' => 'Which of the following is not a keyword in java?',
                'answer_1' => 'static',
                'answer_2' => 'Boolean',
                'answer_3' => 'void',
                'answer_4' => 'private',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 63,
                'weightage' => 53.0,
                'levels' => 'Hard',
            ),
            24 => 
            array (
                'question_id' => 25,
                'question_text' => 'What is the default value of byte variable?',
                'answer_1' => '0',
                'answer_2' => '0',
                'answer_3' => NULL,
                'answer_4' => 'not defined',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 29,
                'weightage' => 17.0,
                'levels' => 'Easy',
            ),
            25 => 
            array (
                'question_id' => 26,
                'question_text' => 'What is JRE?',
                'answer_1' => 'JRE is a java based GUI application.',
                'answer_2' => 'JRE is an application development framework.',
                'answer_3' => 'RE is an implementation of the Java Virtual Machine which executes Java programs.',
                'answer_4' => 'None of the above.',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 55,
                'weightage' => 25.0,
                'levels' => 'Easy',
            ),
            26 => 
            array (
                'question_id' => 27,
                'question_text' => 'Dynamic binding uses which information for binding?',
                'answer_1' => 'type',
                'answer_2' => 'object',
                'answer_3' => 'Both of above',
                'answer_4' => 'None of the above.',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 87,
                'weightage' => 75.0,
                'levels' => 'Hard',
            ),
            27 => 
            array (
                'question_id' => 28,
                'question_text' => 'Which arithmetic operations can result in the throwing of an Arithmetic Exception?',
                'answer_1' => '- %',
                'answer_2' => '* - +',
                'answer_3' => '! - -',
                'answer_4' => '>>- <<',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 71,
                'weightage' => 98.0,
                'levels' => 'Expert',
            ),
            28 => 
            array (
                'question_id' => 29,
                'question_text' => 'Java is a',
                'answer_1' => 'high-level programming language',
            'answer_2' => 'object-oriented (class-based) programming language',
                'answer_3' => 'functional- imperative and reflective programming language',
                'answer_4' => 'All the above',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 94,
                'weightage' => 66.0,
                'levels' => 'Hard',
            ),
            29 => 
            array (
                'question_id' => 30,
                'question_text' => 'Which allows the removal of elements from a collection?',
                'answer_1' => 'Enumeration',
                'answer_2' => 'Iterator',
                'answer_3' => 'Both',
                'answer_4' => 'None of the above',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 57,
                'weightage' => 35.0,
                'levels' => 'Medium',
            ),
            30 => 
            array (
                'question_id' => 31,
                'question_text' => 'Which one could be used as the main container in a Java application?',
                'answer_1' => 'JFrame',
                'answer_2' => 'JPanel',
                'answer_3' => 'JButton',
                'answer_4' => 'Japplet',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 4,
                'weightage' => 78.0,
                'levels' => 'Expert',
            ),
            31 => 
            array (
                'question_id' => 32,
                'question_text' => 'A UML association from class A to class B means',
                'answer_1' => 'Class B inherits from Class A',
                'answer_2' => 'Class A has an attribute of type B',
                'answer_3' => 'Class B has an attribute of type A',
                'answer_4' => 'Class B is defined within class A',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 46,
                'weightage' => 83.0,
                'levels' => 'Expert',
            ),
            32 => 
            array (
                'question_id' => 33,
                'question_text' => 'How can you prevent a member variable from becoming serialized?',
                'answer_1' => 'By marking it volatile',
                'answer_2' => 'By marking it private',
                'answer_3' => 'By marking it transient',
                'answer_4' => 'You can not.',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 19,
                'weightage' => 79.0,
                'levels' => 'Expert',
            ),
            33 => 
            array (
                'question_id' => 34,
                'question_text' => 'A UML association is ...',
                'answer_1' => 'Implemented as a Java method',
                'answer_2' => 'Implemented as a sub-class',
                'answer_3' => 'Implemented as a Java attribute member',
                'answer_4' => 'Implemented as a String constructor returning the name of the association target',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 58,
                'weightage' => 47.0,
                'levels' => 'Medium',
            ),
            34 => 
            array (
                'question_id' => 35,
            'question_text' => 'What would display from the following statements? int [ ] nums = {1-2-3-4-5-6}; System.out.println((nums[1] + nums[3]));',
                'answer_1' => '2+4',
                'answer_2' => '6',
                'answer_3' => '4',
                'answer_4' => '1+3',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 3,
                'activity_idFK' => 29,
                'weightage' => 99.0,
                'levels' => 'Expert',
            ),
            35 => 
            array (
                'question_id' => 36,
                'question_text' => 'The science of 2 is concerned with which of the following matters?',
                'answer_1' => 'applying 2 principles',
                'answer_2' => 'describing the physical world',
                'answer_3' => 'making predictions about a broad range of phenomena',
                'answer_4' => 'all of these',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 73,
                'weightage' => 51.0,
                'levels' => 'Hard',
            ),
            36 => 
            array (
                'question_id' => 37,
                'question_text' => 'A useful method of expressing very small or very large number is',
                'answer_1' => 'Arabic numerals',
                'answer_2' => 'Greek letters',
                'answer_3' => 'significant figures',
                'answer_4' => 'scientific notation',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 78,
                'weightage' => 61.0,
                'levels' => 'Hard',
            ),
            37 => 
            array (
                'question_id' => 38,
                'question_text' => 'Which among the following correctly defines the First Law of Thermodynamics?',
                'answer_1' => 'The law of conservation of energy',
                'answer_2' => 'Newtons law of gravitation',
                'answer_3' => 'Archimedes principle',
                'answer_4' => 'Charles law',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 71,
                'weightage' => 48.0,
                'levels' => 'Medium',
            ),
            38 => 
            array (
                'question_id' => 39,
                'question_text' => 'The device- which is used to detect the presence of oil on water surface- is known as …',
                'answer_1' => 'Gyroscope',
                'answer_2' => 'Gravometer',
                'answer_3' => 'Fethometer',
                'answer_4' => 'Dip circle',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 18,
                'weightage' => 56.0,
                'levels' => 'Hard',
            ),
            39 => 
            array (
                'question_id' => 40,
                'question_text' => 'Which among the following influences the pitch of sounds?',
                'answer_1' => 'Velocity',
                'answer_2' => 'Frequency',
                'answer_3' => 'Wavelength',
                'answer_4' => 'Amplitude',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 76,
                'weightage' => 38.0,
                'levels' => 'Medium',
            ),
            40 => 
            array (
                'question_id' => 41,
                'question_text' => 'No matter how far someone is standing from the mirror- the image appears erect. The mirror is',
                'answer_1' => 'Only plane',
                'answer_2' => 'Only convex',
                'answer_3' => 'Only concave',
                'answer_4' => 'Either plane or convex',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 27,
                'weightage' => 20.0,
                'levels' => 'Easy',
            ),
            41 => 
            array (
                'question_id' => 42,
                'question_text' => 'The optical power of a lens is measured in',
                'answer_1' => 'Tesla',
                'answer_2' => 'Ounce',
                'answer_3' => 'Diopter',
                'answer_4' => 'Pint',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 5,
                'weightage' => 87.0,
                'levels' => 'Expert',
            ),
            42 => 
            array (
                'question_id' => 43,
                'question_text' => 'The measuring unit of an angle is:',
                'answer_1' => 'Lux',
                'answer_2' => 'Farad',
                'answer_3' => 'Steradian',
                'answer_4' => 'Radian',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 46,
                'weightage' => 73.0,
                'levels' => 'Hard',
            ),
            43 => 
            array (
                'question_id' => 44,
                'question_text' => 'Who had invented Transformer?',
                'answer_1' => 'Baird',
                'answer_2' => 'Faraday',
                'answer_3' => 'Ginsberg',
                'answer_4' => 'Thomson',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 15,
                'weightage' => 5.0,
                'levels' => 'Easy',
            ),
            44 => 
            array (
                'question_id' => 45,
                'question_text' => 'Through a beam of red light a diffraction pattern is obtained; what will happen if red light is replaced by blue light?',
                'answer_1' => 'No change',
                'answer_2' => 'Bands will disappear',
                'answer_3' => 'Diffraction patter will become broader and further apart',
                'answer_4' => 'Diffraction pattern will become narrower and crowed together',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 35,
                'weightage' => 6.0,
                'levels' => 'Easy',
            ),
            45 => 
            array (
                'question_id' => 46,
                'question_text' => 'Which among the following is used to see the objects above the sea level?',
                'answer_1' => 'Periscope',
                'answer_2' => 'Manometer',
                'answer_3' => 'Machmeter',
                'answer_4' => 'Kymograph',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 31,
                'weightage' => 15.0,
                'levels' => 'Easy',
            ),
            46 => 
            array (
                'question_id' => 47,
                'question_text' => 'Which among the following waves possess the lowest amount of energy?',
                'answer_1' => 'Gamma rays',
                'answer_2' => 'Radio waves',
                'answer_3' => 'X rays',
                'answer_4' => 'Ultraviolet rays',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 49,
                'weightage' => 55.0,
                'levels' => 'Hard',
            ),
            47 => 
            array (
                'question_id' => 48,
                'question_text' => 'Which of these express a vector quantity?',
                'answer_1' => '10kg',
                'answer_2' => '10kg to the north',
                'answer_3' => '10 ms',
                'answer_4' => '10 ms to the east',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 10:24:03',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 50,
                'weightage' => 42.0,
                'levels' => 'Medium',
            ),
            48 => 
            array (
                'question_id' => 49,
                'question_text' => 'Which one of the following is an example of a vector quantity?',
                'answer_1' => 'Area',
                'answer_2' => 'Mass',
                'answer_3' => 'Velocity',
                'answer_4' => 'Distance',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 10:24:03',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 2,
                'weightage' => -1.0,
                'levels' => 'Expert',
            ),
            49 => 
            array (
                'question_id' => 50,
                'question_text' => 'Which statement describes a vector?',
                'answer_1' => 'It has magnitude but no direction',
                'answer_2' => 'It has direction but no magnitude',
                'answer_3' => 'It has both direction and magnitude',
                'answer_4' => 'It has constant magnitude but no',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 10:24:03',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 61,
                'weightage' => 1.0,
                'levels' => 'Hard',
            ),
            50 => 
            array (
                'question_id' => 51,
                'question_text' => 'If a boomerang is thrown 20 m in a straight line and returns exactly to the spot it was thrown what is its displacement?',
                'answer_1' => '20m',
                'answer_2' => '40m',
                'answer_3' => '0m',
                'answer_4' => '-20m',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 10:24:03',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 98,
                'weightage' => 1.0,
                'levels' => 'Expert',
            ),
            51 => 
            array (
                'question_id' => 52,
                'question_text' => 'A car moved 60 km East and 90 km West. What is the distance it traveled?',
                'answer_1' => '30 km- West',
                'answer_2' => '60 km. East',
                'answer_3' => '90 km',
                'answer_4' => '150 km',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 10:24:03',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 8,
                'weightage' => -1.0,
                'levels' => 'Easy',
            ),
            52 => 
            array (
                'question_id' => 53,
                'question_text' => 'If a car moves 12 km North- 19 km East- and 12 km South- what is its displacement?',
                'answer_1' => '12 km',
                'answer_2' => '19 km- East',
                'answer_3' => '31 Km',
                'answer_4' => '43 Km- East',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 10:24:03',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 44,
                'weightage' => 1.0,
                'levels' => 'Medium',
            ),
            53 => 
            array (
                'question_id' => 54,
                'question_text' => 'The presidents airplane- Air Force One- flies at 250 ms to the east with respect to the air. The air is moving at 35 ms to the north with respect to the ground. Find the velocity of Air Force One with respect to the ground.',
                'answer_1' => '252 ms',
                'answer_2' => '222 ms',
                'answer_3' => '435 ms',
                'answer_4' => '125 ms',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 96,
                'weightage' => 82.0,
                'levels' => 'Expert',
            ),
            54 => 
            array (
                'question_id' => 55,
                'question_text' => 'A motorboat- which has a speed of 5 meters per second in still water- is headed east as it crosses a river flowing south at 3.3 meters per second. What is the magnitude of the boats resultant velocity with respect to the starting point?',
                'answer_1' => '3.3 ms',
                'answer_2' => '5.0 ms',
                'answer_3' => '6.0 ms',
                'answer_4' => '8.3 ms',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 48,
                'weightage' => 95.0,
                'levels' => 'Expert',
            ),
            55 => 
            array (
                'question_id' => 56,
                'question_text' => 'A person observes a fireworks display from a safe distance of 0.750 kilometer. Assuming that sound travels at 340 meters per second in air- what is the time between the person seeing and hearing a fireworks explosion?',
                'answer_1' => '0.453 s',
                'answer_2' => '2.21 s',
                'answer_3' => '410 s',
                'answer_4' => '255-000 s',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 51,
                'weightage' => 27.0,
                'levels' => 'Medium',
            ),
            56 => 
            array (
                'question_id' => 57,
                'question_text' => 'A child walks 5 meters north- then 4 meters east- and finally 2 meters south. What is the magnitude of the resultant displacement of the child after the entire walk?',
                'answer_1' => '1.0 m',
                'answer_2' => '5.0 m',
                'answer_3' => '3.0 m',
                'answer_4' => '11.0 m',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 12,
                'weightage' => 49.0,
                'levels' => 'Medium',
            ),
            57 => 
            array (
                'question_id' => 58,
                'question_text' => 'A fishing boat with a maximum speed of 3 ms relative to the water is in a river that is flowing at 2 ms. What is the maximum speed the boat can obtain relative to the shore?',
                'answer_1' => '5 ms',
                'answer_2' => '25 ms',
                'answer_3' => '5.8 ms',
                'answer_4' => '7 ms',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 6,
                'weightage' => 64.0,
                'levels' => 'Hard',
            ),
            58 => 
            array (
                'question_id' => 59,
                'question_text' => 'A plane traveling north at 150 ms is flying toward a runway. A cross-wind of 30 ms begins to blow from the east. The pilot realizes he is being blown off course. At what angle must he head in order to travel directly north?',
                'answer_1' => '19 degrees east of north',
                'answer_2' => '29 degrees east of north',
                'answer_3' => '19 degrees west of north',
                'answer_4' => '29 degrees east of south',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 5,
                'activity_idFK' => 94,
                'weightage' => 74.0,
                'levels' => 'Hard',
            ),
            59 => 
            array (
                'question_id' => 60,
                'question_text' => 'Which of the following statement is best in accordance with Kepler\'s first law of planetary motion?',
                'answer_1' => 'The orbits of planets form an ellipse- with the Sun at one focus.',
                'answer_2' => 'Planets orbit in perfect circles- with the Sun slightly off-center.',
                'answer_3' => 'All planets make one orbit of the Sun in exactly the same time period.',
                'answer_4' => 'Planets farther from the Sun orbit proportionally faster.',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 15:14:07',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 49,
                'weightage' => 80.0,
                'levels' => 'Expert',
            ),
            60 => 
            array (
                'question_id' => 61,
                'question_text' => 'A total eclipse of the Sun occurs when the disc-like shape of the Moon completely covers the Sun- as seen from locations on Earth. However- this depends on the Moon being at its closest point to Earth in its orbit. Some eclipses- known as annular eclipses- show a thin ring of bright sunlight visible around the dark disc of the Moon. What is the relative position of the Moon- the Sun- and Earth during an annular eclipse?',
                'answer_1' => 'The Moon is at apogee.',
                'answer_2' => 'The Moon is at perigee.',
                'answer_3' => 'Earth is at aphelion.',
                'answer_4' => 'Earth is at perihelion.',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 15:14:07',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 64,
                'weightage' => 69.5,
                'levels' => 'Hard',
            ),
            61 => 
            array (
                'question_id' => 62,
                'question_text' => 'Because of its changing proximity to the Sun- which property does Kepler\'s Second Law of Planetary Motion predict will change during a planet\'s orbit?',
                'answer_1' => 'orbital period',
                'answer_2' => 'orbital minor axis',
                'answer_3' => 'orbital speed',
                'answer_4' => 'orbital eccentricity',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 15:14:07',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 71,
                'weightage' => 11.5,
                'levels' => 'Easy',
            ),
            62 => 
            array (
                'question_id' => 63,
            'question_text' => 'Planets orbit the Sun in a shape called a(n)',
                'answer_1' => 'circle',
                'answer_2' => 'ellipse',
                'answer_3' => 'focus',
                'answer_4' => 'perihelion',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 15:14:08',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 64,
                'weightage' => 50.5,
                'levels' => 'Medium',
            ),
            63 => 
            array (
                'question_id' => 64,
                'question_text' => 'An ellipse is drawn around two points called',
                'answer_1' => 'aphelion',
                'answer_2' => 'perihelion',
                'answer_3' => 'foci',
                'answer_4' => 'axis',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 15:14:08',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 5,
                'weightage' => 12.5,
                'levels' => 'Easy',
            ),
            64 => 
            array (
                'question_id' => 65,
                'question_text' => 'When a planet orbits the Sun- one of the foci of the elliptical orbit is',
                'answer_1' => 'the axis',
                'answer_2' => 'the perihelion',
                'answer_3' => 'the center',
                'answer_4' => 'the Sun',
                'correct' => 'answer_4',
                'created_at' => NULL,
                'updated_at' => '2023-02-15 15:14:08',
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 33,
                'weightage' => 16.5,
                'levels' => 'Easy',
            ),
            65 => 
            array (
                'question_id' => 66,
                'question_text' => 'Kepler\'s 2nd Law deals with',
                'answer_1' => 'the shape of the planets\' orbits',
                'answer_2' => 'the speedarea the planet travels',
                'answer_3' => 'the length of time it takes the planet to orbit the sun',
                'answer_4' => 'aphelion',
                'correct' => 'answer_2',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 51,
                'weightage' => 44.0,
                'levels' => 'Medium',
            ),
            66 => 
            array (
                'question_id' => 67,
                'question_text' => 'Kepler\'s third law of planetary motion describes a relationship between the',
                'answer_1' => 'shape of orbit and location of Sun.',
                'answer_2' => 'orbital velocity and position in orbit',
                'answer_3' => 'distance from the Sun and length of year.',
                'answer_4' => 'path of epicycle and position.',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 55,
                'weightage' => 69.0,
                'levels' => 'Hard',
            ),
            67 => 
            array (
                'question_id' => 68,
                'question_text' => 'Keplers laws of planetary motion replaced circular orbits with',
                'answer_1' => 'elliptical orbits',
                'answer_2' => 'parabolic orbits',
                'answer_3' => 'conical orbits',
                'answer_4' => 'hyperbolic orbits',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 23,
                'weightage' => 11.0,
                'levels' => 'Easy',
            ),
            68 => 
            array (
                'question_id' => 69,
                'question_text' => 'Keplers laws of planetary motion were proposed only for',
                'answer_1' => 'our sun',
                'answer_2' => 'any star in our galaxy',
                'answer_3' => 'any star in the universe',
                'answer_4' => 'stars of other solar systems',
                'correct' => 'answer_1',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 49,
                'weightage' => 50.0,
                'levels' => 'Medium',
            ),
            69 => 
            array (
                'question_id' => 70,
                'question_text' => 'What does Keplers law of period relate?',
                'answer_1' => 'Time period and semi-minor axis',
                'answer_2' => 'Time period and eccentricity',
                'answer_3' => 'Time period and semi-major axis',
                'answer_4' => 'Time period and area swept by the planet',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 74,
                'weightage' => 15.0,
                'levels' => 'Easy',
            ),
            70 => 
            array (
                'question_id' => 71,
                'question_text' => 'What is the constant of proportionality in Keplers law of periods known as?',
                'answer_1' => 'Universal gravitational constant',
                'answer_2' => 'Escape velocity',
                'answer_3' => 'There is no constant of proportionality',
                'answer_4' => 'Cannot be determined',
                'correct' => 'answer_3',
                'created_at' => NULL,
                'updated_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 2,
                'topic_idFK' => 6,
                'activity_idFK' => 21,
                'weightage' => 25.0,
                'levels' => 'Easy',
            ),
            71 => 
            array (
                'question_id' => 72,
                'question_text' => 'This is question no 1',
                'answer_1' => 'Option 1',
                'answer_2' => 'Option 2',
                'answer_3' => 'Option 3',
                'answer_4' => 'Option 4',
                'correct' => 'answer_2',
                'created_at' => '2023-01-18 13:29:43',
                'updated_at' => '2023-01-18 13:29:43',
                'created_by' => 49,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 85,
                'weightage' => 81.0,
                'levels' => 'Expert',
            ),
            72 => 
            array (
                'question_id' => 73,
                'question_text' => 'Question no 2',
                'answer_1' => 'option 1',
                'answer_2' => 'option 2',
                'answer_3' => 'option 3',
                'answer_4' => 'option 4',
                'correct' => 'answer_1',
                'created_at' => '2023-01-18 13:42:45',
                'updated_at' => '2023-01-18 13:42:45',
                'created_by' => 49,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 2,
                'topic_idFK' => 4,
                'activity_idFK' => 62,
                'weightage' => 29.0,
                'levels' => 'Medium',
            ),
            73 => 
            array (
                'question_id' => 74,
                'question_text' => 'The other question',
                'answer_1' => 'Option 1',
                'answer_2' => 'Option 2',
                'answer_3' => 'Option 3',
                'answer_4' => 'Option 4',
                'correct' => 'answer_2',
                'created_at' => '2023-01-18 19:16:22',
                'updated_at' => '2023-01-18 19:16:22',
                'created_by' => 49,
                'updated_by' => NULL,
                'type_of_assessment' => 'post',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 54,
                'weightage' => 99.0,
                'levels' => 'Expert',
            ),
            74 => 
            array (
                'question_id' => 75,
                'question_text' => 'Testing my Question 1',
                'answer_1' => 'A',
                'answer_2' => 'B',
                'answer_3' => 'C',
                'answer_4' => 'D',
                'correct' => 'answer_2',
                'created_at' => '2023-02-14 12:30:14',
                'updated_at' => '2023-02-14 12:30:14',
                'created_by' => 49,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 84,
                'weightage' => 9.0,
                'levels' => 'Easy',
            ),
            75 => 
            array (
                'question_id' => 76,
                'question_text' => 'Testing my Question 2',
                'answer_1' => 'D',
                'answer_2' => 'C',
                'answer_3' => 'B',
                'answer_4' => 'A',
                'correct' => 'answer_2',
                'created_at' => '2023-02-15 09:39:58',
                'updated_at' => '2023-02-15 09:39:58',
                'created_by' => 49,
                'updated_by' => NULL,
                'type_of_assessment' => 'pre',
                'course_idFK' => 1,
                'topic_idFK' => 1,
                'activity_idFK' => 55,
                'weightage' => 48.0,
                'levels' => 'Medium',
            ),
        ));
        
        
    }
}